parameters:
    sb_json_rpc.jsonrpccontroller.class: Sb\JsonRpcBundle\Controller\JsonRpcController

services:
    sb_json_rpc.jsonrpccontroller:
        public: true
        class: '%sb_json_rpc.jsonrpccontroller.class%'
        arguments: ['@service_container', '%sb.json_rpc%']
