parameters:
    sb_json_rpc.jsonrpccontroller.class: Sb\JsonRpcBundle\Controller\JsonRpcController

services:
    sb_json_rpc.jsonrpccontroller:
        autowire: true
        autoconfigure: true
        class: '%sb_json_rpc.jsonrpccontroller.class%'
        tags: [ 'controller.service_arguments' ]